export const GET_MESSAGES_REQUEST = "GET_MESSAGES_REQUEST"
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS"
export const GET_MESSAGES_FAILURE = "GET_MESSAGES_FAILURE"

export const GET_CHOSEN_USER_MESSAGES_REQUEST = "GET_CHOSEN_USER_MESSAGES_REQUEST"
export const GET_CHOSEN_USER_MESSAGES_SUCCESS = "GET_CHOSEN_USER_MESSAGES_SUCCESS"
export const GET_CHOSEN_USER_MESSAGES_FAILURE = "GET_CHOSEN_USER_MESSAGES_FAILURE"

export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST"
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS"
export const SEND_MESSAGE_FAILURE = "SEND_MESSAGE_FAILURE"