export const GET_MESSAGES_REQUEST = "GET_MESSAGES_REQUEST"
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS"
export const GET_MESSAGES_FAILURE = "GET_MESSAGES_FAILURE"

export const GET_CHOOSEN_USER_MESSAGES_REQUEST = "GET_CHOOSEN_USER_MESSAGES_REQUEST"
export const GET_CHOOSEN_USER_MESSAGES_SUCCESS = "GET_CHOOSEN_USER_MESSAGES_SUCCESS"
export const GET_CHOOSEN_USER_MESSAGES_FAILURE = "GET_CHOOSEN_USER_MESSAGES_FAILURE"

