export const GET_ALLPRODUCTS_REQUEST = "GET_ALLPRODUCTS_REQUEST"
export const GET_ALLPRODUCTS_SUCCESS = "GET_ALLPRODUCTS_SUCCESS"
export const GET_ALLPRODUCTS_FAILURE = "GET_ALLPRODUCTS_FAILURE"

export const GET_PRODUCTDETAILS_REQUEST = "GET_PRODUCTDETAILS_REQUEST"
export const GET_PRODUCTDETAILS_SUCCESS = "GET_PRODUCTDETAILS_SUCCESS"
export const GET_PRODUCTDETAILS_FAILURE = "GET_PRODUCTDETAILS_FAILURE"

export const GET_SEARCH_FOR_PRODUCT_REQUEST = "GET_SEARCH_FOR_PRODUCT_REQUEST"
export const GET_SEARCH_FOR_PRODUCT_SUCCESS = "GET_SEARCH_FOR_PRODUCT_SUCCESS"
export const GET_SEARCH_FOR_PRODUCT_FAILURE = "GET_SEARCH_FOR_PRODUCT_FAILURE"
