// export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST"
// export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS"
// export const CREATE_PRODUCT_FAILURE = "CREATE_PRODUCT_FAILURE"

export const GET_ALLPRODUCTS_REQUEST = "GET_ALLPRODUCTS_REQUEST"
export const GET_ALLPRODUCTS_SUCCESS = "GET_ALLPRODUCTS_SUCCESS"
export const GET_ALLPRODUCTS_FAILURE = "GET_ALLPRODUCTS_FAILURE"

// export const DELETE_PRODUCTS_REQUEST = "DELETE_PRODUCTS_REQUEST"
// export const DELETE_PRODUCTS_SUCCESS = "DELETE_PRODUCTS_SUCCESS"
// export const DELETE_PRODUCTS_FAILURE = "DELETE_PRODUCTS_FAILURE"
//
// export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST"
// export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
// export const UPDATE_PRODUCT_FAILURE = "UPDATE_PRODUCT_FAILURE"
