export const GET_SAVEDFORLATER_REQUEST = "GET_SAVEDFORLATER_REQUEST"
export const GET_SAVEDFORLATER_SUCCESS = "GET_SAVEDFORLATER_SUCCESS"
export const GET_SAVEDFORLATER_FAILURE = "GET_SAVEDFORLATER_FAILURE"
