export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE"

export const GET_FROM_CART_REQUEST = "GET_FROM_CART_REQUEST"
export const GET_FROM_CART_SUCCESS = "GET_FROM_CART_SUCCESS"
export const GET_FROM_CART_FAILURE = "GET_FROM_CART_FAILURE"

export const REMOVE_FROM_CART_REQUEST = "REMOVE_FROM_CART_REQUEST"
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS"
export const REMOVE_FROM_CART_FAILURE = "REMOVE_FROM_CART_FAILURE"

export const GUEST_PRODUCT_GET_REQUEST = "GUEST_PRODUCT_GET_REQUEST"
export const GUEST_PRODUCT_GET_SUCCESS = "GUEST_PRODUCT_GET_SUCCESS"
export const GUEST_PRODUCT_GET_FAILURE = "GUEST_PRODUCT_GET_FAILURE"

// export const GUEST_PRODUCT_REMOVE_REQUEST = "GUEST_PRODUCT_REMOVE_REQUEST"
// export const GUEST_PRODUCT_REMOVE_SUCCESS = "GUEST_PRODUCT_REMOVE_SUCCESS"
// export const GUEST_PRODUCT_REMOVE_FAILURE = "GUEST_PRODUCT_REMOVE_FAILURE"
