export const SAVE_PRODUCT_FOR_LATER_REQUEST = "SAVE_PRODUCT_FOR_LATER_REQUEST"
export const SAVE_PRODUCT_FOR_LATER_SUCCESS = "SAVE_PRODUCT_FOR_LATER_SUCCESS"
export const SAVE_PRODUCT_FOR_LATER_FAILURE = "SAVE_PRODUCT_FOR_LATER_FAILURE"

export const GET_PRODUCTS_FOR_LATER_REQUEST = "GET_PRODUCTS_FOR_LATER_REQUEST"
export const GET_PRODUCTS_FOR_LATER_SUCCESS = "GET_PRODUCTS_FOR_LATER_SUCCESS"
export const GET_PRODUCTS_FOR_LATER_FAILURE = "GET_PRODUCTS_FOR_LATER_FAILURE"

export const REMOVE_PRODUCT_FOR_LATER_REQUEST = "REMOVE_PRODUCT_FOR_LATER_REQUEST"
export const REMOVE_PRODUCT_FOR_LATER_SUCCESS = "REMOVE_PRODUCT_FOR_LATER_SUCCESS"
export const REMOVE_PRODUCT_FOR_LATER_FAILURE = "REMOVE_PRODUCT_FOR_LATER_FAILURE"
