export const CREATE_PRODUCT_COMMENT_REQUEST = "CREATE_PRODUCT_COMMENT_REQUEST"
export const CREATE_PRODUCT_COMMENT_SUCCESS = "CREATE_PRODUCT_COMMENT_SUCCESS"
export const CREATE_PRODUCT_COMMENT_FAILURE = "CREATE_PRODUCT_COMMENT_FAILURE"

export const GET_PRODUCTS_COMMENT_REQUEST = "GET_PRODUCTS_COMMENT_REQUEST"
export const GET_PRODUCTS_COMMENT_SUCCESS = "GET_PRODUCTS_COMMENT_SUCCESS"
export const GET_PRODUCTS_COMMENT_FAILURE = "GET_PRODUCTS_COMMENT_FAILURE"

export const DELETE_PRODUCTS_COMMENT_REQUEST = "DELETE_PRODUCTS_COMMENT_REQUEST"
export const DELETE_PRODUCTS_COMMENT_SUCCESS = "DELETE_PRODUCTS_COMMENT_SUCCESS"
export const DELETE_PRODUCTS_COMMENT_FAILURE = "DELETE_PRODUCTS_COMMENT_FAILURE"