export const GET_PRODUCTS_LIKE_REQUEST = "GET_PRODUCTS_LIKE_REQUEST"
export const GET_PRODUCTS_LIKE_SUCCESS = "GET_PRODUCTS_LIKE_SUCCESS"
export const GET_PRODUCTS_LIKE_FAILURE = "GET_PRODUCTS_LIKE_FAILURE"

export const LIKE_PRODUCTS_REQUEST = "LIKE_PRODUCTS_REQUEST"
export const LIKE_PRODUCTS_SUCCESS = "LIKE_PRODUCTS_SUCCESS"
export const LIKE_PRODUCTS_FAILURE = "LIKE_PRODUCTS_FAILURE"

export const UNLIKE_PRODUCTS_REQUEST = "UNLIKE_PRODUCTS_REQUEST"
export const UNLIKE_PRODUCTS_SUCCESS = "UNLIKE_PRODUCTS_SUCCESS"
export const UNLIKE_PRODUCTS_FAILURE = "UNLIKE_PRODUCTS_FAILURE"