export const CREATE_ADDRESS_REQUEST = "CREATE_ADDRESS_REQUEST"
export const CREATE_ADDRESS_SUCCESS = "CREATE_ADDRESS_SUCCESS"
export const CREATE_ADDRESS_FAILURE = "CREATE_ADDRESS_FAILURE"

export const GET_ADDRESS_REQUEST = "GET_ADDRESS_REQUEST"
export const GET_ADDRESS_SUCCESS = "GET_ADDRESS_SUCCESS"
export const GET_ADDRESS_FAILURE = "GET_ADDRESS_FAILURE"

export const DELETE_ADDRESS_REQUEST = "DELETE_ADDRESS_REQUEST"
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS"
export const DELETE_ADDRESS_FAILURE = "DELETE_ADDRESS_FAILURE"

export const DEFAULT_ADDRESS_REQUEST = "DEFAULT_ADDRESS_REQUEST"
export const DEFAULT_ADDRESS_SUCCESS = "DEFAULT_ADDRESS_SUCCESS"
export const DEFAULT_ADDRESS_FAILURE = "DEFAULT_ADDRESS_FAILURE"
