export const ADD_CATEGORY_REQUEST = "ADD_CATEGORY_REQUEST"
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS"
export const ADD_CATEGORY_FAILURE = "ADD_CATEGORY_FAILURE"

export const GET_PRODUCT_CATEGORIES_REQUEST = "GET_PRODUCT_CATEGORIES_REQUEST"
export const GET_PRODUCT_CATEGORIES_SUCCESS = "GET_PRODUCT_CATEGORIES_SUCCESS"
export const GET_PRODUCT_CATEGORIES_FAILURE = "GET_PRODUCT_CATEGORIES_FAILURE"

export const REMOVE_CATEGORY_REQUEST = "REMOVE_CATEGORY_REQUEST"
export const REMOVE_CATEGORY_SUCCESS = "REMOVE_CATEGORY_SUCCESS"
export const REMOVE_CATEGORY_FAILURE = "REMOVE_CATEGORY_FAILURE"

// export const GUEST_PRODUCT_GET_REQUEST = "GUEST_PRODUCT_GET_REQUEST"
// export const GUEST_PRODUCT_GET_SUCCESS = "GUEST_PRODUCT_GET_SUCCESS"
// export const GUEST_PRODUCT_GET_FAILURE = "GUEST_PRODUCT_GET_FAILURE"
//
// export const BUY_PRODUCTS_FROM_CART_REQUEST = "BUY_PRODUCTS_FROM_CART_REQUEST"
// export const BUY_PRODUCTS_FROM_CART_SUCCESS = "BUY_PRODUCTS_FROM_CART_SUCCESS"
// export const BUY_PRODUCTS_FROM_CART_FAILURE = "BUY_PRODUCTS_FROM_CART_FAILURE"
//
// export const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST"
// export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS"
// export const GET_ORDERS_FAILURE = "GET_ORDERS_FAILURE"
