export const GET_ALL_USER_PRODUCTS_REQUEST = "GET_ALL_USER_PRODUCTS_REQUEST"
export const GET_ALL_USER_PRODUCTS_SUCCESS = "GET_ALL_USER_PRODUCTS_SUCCESS"
export const GET_ALL_USER_PRODUCTS_FAILURE = "GET_ALL_USER_PRODUCTS_FAILURE"
