export const GET_ALL_USER_PRODUCTS_REQUEST = "GET_ALL_USER_PRODUCTS_REQUEST"
export const GET_ALL_USER_PRODUCTS_SUCCESS = "GET_ALL_USER_PRODUCTS_SUCCESS"
export const GET_ALL_USER_PRODUCTS_FAILURE = "GET_ALL_USER_PRODUCTS_FAILURE"

export const DELETE_USER_PRODUCT_REQUEST = "DELETE_USER_PRODUCT_REQUEST"
export const DELETE_USER_PRODUCT_SUCCESS = "DELETE_USER_PRODUCT_SUCCESS"
export const DELETE_USER_PRODUCT_FAILURE = "DELETE_USER_PRODUCT_FAILURE"

export const UPDATE_USER_PRODUCT_REQUEST = "UPDATE_USER_PRODUCT_REQUEST"
export const UPDATE_USER_PRODUCT_SUCCESS = "UPDATE_USER_PRODUCT_SUCCESS"
export const UPDATE_USER_PRODUCT_FAILURE = "UPDATE_USER_PRODUCT_FAILURE"
